name: Node.js CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        mongodb-version: ['8.0']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017

      - name: Create .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: npm ci

      - name: Disable NEXT.JS telemetry
        run: npx next telemetry disable

      - name: Run Build
        run: npm run build